const translations = {
	'#/START': 'Startseite',
	'#/OVERVIEW': 'Übersicht',
	'#/STATUS': 'Status',
	'#/CALENDAR': 'Kalender',
	'#/ANALYSIS': 'Auswertung',
	'#/CONFIG': 'Konfiguration',
	'#/INSPECTION': 'NK-Kontrolle',
	'#/ABOUT': 'Über Upupua',
	'#/DATABASE': 'Datenbank',
	"ALL_SPECIES": "Alle Arten",
	"ARCHITECTURE": "Bauart",
	"ARCHITECTURES": "Bauarten",
	"BANDINGWINDOWSTART": "Beringung ab",
	"BANDINGWINDOWEND": "Beringung bis",
	"BAND_STATUS_PARENTS": "Beringung Altvögel",
	"BAND_STATUS_NESTLINGS": "Beringung Nestlinge",
	"BOXES": "Nistkästen",
	"BOX.NAME": "Beschriftung",
	"BOX.LAT": "Breitengrad",
	"BOX.LON": "Längengrad",
	"BOX.POSITIONING_DISABLED": "Position beibehalten",
	"BOX.POSITIONING_CORRECTION": "Position korrigieren",
	"BOX.POSITIONING_NEW_LOCATION": "Nistkasten umhängen",
	"BOX.VALIDFROM": "Aufgehängt am",
	"BOX.VALIDUNTIL": "Abgehängt am",
	"CLUTCHSIZE": "Gelegegröße",
	"DATE": "Datum",
	"DB_NAME": "Datenbank-Name",
	"DOC_COUNT": "Einträge",
	"EGGS": "Eier",
	"ENTRANCEWIDTH": "Flugloch-Breite (mm)",
	"ENTRANCEHEIGHT": "Flugloch-Höhe (mm)",
	"ENTRANCECOUNT": "Anzahl Fluglöcher",
	"FAILURE": "Misserfolg",
	"HOSTNAME": "Hostname",
	"STATE_NESTLINGS.INSPECTION.NESTLINGS": "Lebende Nestlinge",
	"STATE_SUCCESS.INSPECTION.NESTLINGS": "Ausgeflogene Nestlinge",
	"INCUBATION": "Brutdauer",
	"INSPECTION.NESTLINGSBANDED": "Anzahl beringter Nestlinge",
	"INSPECTION.NESTLINGSAGE": "Alter der Nestlinge (Tage)",
	"NAME": "Name",
	"PREDATOR": "Prädator",
	"OCCUPANCY": "Belegung",
	"OCCUPATOR": "Eindringling",
	"STATE_EMPTY": "Leer",
	"STATE_NEST_BUILDING": "Nestbau",
	"STATE_NEST_READY": "Legebereit",
	"STATE_EGGS": "Eier",
	"STATE_BREEDING": "Brütend",
	"STATE_NESTLINGS": "Nestlinge",
	"STATE_FAILURE": "Misserfolg",
	"STATE_SUCCESS": "Erfolg",
	"STATE_OCCUPIED": "Okkupiert",
	"STATE_ABANDONED": "Verlassen",
	
	"LAST_INSPECTION": "Letzte Inspektion",
	"PERPETRATOR": "Eindringling",
	"PERPETRATORS": "Eindringlinge",
	"PREDATION.PERPETRATOR": "Prädator",
	"NEST_OCCUPATION.PERPETRATOR": "Okkupator",
	"STATUS": "Status",
	"SPECIES": "Vogelart",
	"SUCCESS": "Erfolg",
	"UNKNOWN_FAILURE": "Mißerfolg (Ursache unbekannt)",
	"UNKNOWN_PREDATION": "Prädation (Prädator unbekannt)",
	"USERS.USERNAME": "Benutzername",
	"USERS.PASSWORD": "Passwort",
	"USERS.ROLE.USER": "USER",
	"USERS.ROLE.ADMIN": "ADMIN",
	"USERS.ROLE": "Funktion",
	"PREDATION": "Prädation",
	"NEST_OCCUPATION": "Nest-Okkupation",
	"PARENT_MISSING": "Nest aufgegeben",
	"UNKNOWN": "Unbekannt",
	"HATCHDATE": "Schlüpfdatum",
	"BREEDINGSTART": "Brutbeginn",
	"LAYINGSTART": "Legebeginn"
}

export function translate(str){
	if(str == null) return ''
	var translation
	var arr = str.toUpperCase().split('.')
	while (arr.length && !translation) {
		translation = translations[arr.join('.')]
		arr.shift()
	}
	return translation || str.toUpperCase()
}